### ISSUE TITLE
Keys for jumpword 

### ISSUE THREAD

**Issue by akruphi** [axxie/far2l-jumpword#3]
Thank you for useful far2l-plugin :+1: 

In my systems combinations **Ctrl-Alt-...** grabbed by system for switch workspaces and I recommend use **Ctrl-Shift-** by writing in `~/.config/far2l/settings/key_macros.ini`:
```
[KeyMacros/Editor/CtrlShiftDown]
DisableOutput=0x1
Sequence=F11 J 2
Description=Editor->JumpWord->Below

[KeyMacros/Editor/CtrlShiftUp]
DisableOutput=0x1
Sequence=F11 J 1
Description=Editor->JumpWord->Above
```

**Comment by axxie** [comment]
Yeah, I have similar issue with keys intercepted by Hyper-V.

**Comment by axxie** [comment]
Fixed
